# Your personal GitHub token
github_token: TOKEN
# You can generate it here: https://github.com/settings/tokens
# Guest OS timezone
timezone: UTC
# Are we need check box updates for every 'vagrant up'?
box_check_update: false
# Virtual machine name
machine_name: orion-context-browser
# Virtual machine IP
ip: 192.168.66.66
# Virtual machine CPU cores number
cpus: 1
# Virtual machine RAM
memory: 2048
